## Data Load

In [7]:
import pandas as pd
import numpy as np

# load data
df = pd.read_csv("placementdata.csv")

df.head()

,StudentID,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,1,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,2,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,3,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,4,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,5,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

## Data Prepare

In [8]:
# Remove unnecessary column
df = df.drop(columns=["StudentID"])

# Features and target
X = df.drop("PlacementStatus", axis=1)
y = df["PlacementStatus"]

X.head()

,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks
0,7.5,1,1,1,65,4.4,No,No,61,79
1,8.9,0,3,2,90,4.0,Yes,Yes,78,82
2,7.3,1,2,2,82,4.8,Yes,No,79,80
3,7.5,1,1,2,85,4.4,Yes,Yes,81,80
4,8.3,1,2,2,86,4.5,Yes,Yes,74,88

## Train-Test Split

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)

(8000, 10)

## Model Train

In [10]:
print(df["PlacementStatus"].unique())

['NotPlaced' 'Placed']

In [11]:
print(df.columns)

Index(['CGPA', 'Internships', 'Projects', 'Workshops/Certifications',
       'AptitudeTestScore', 'SoftSkillsRating', 'ExtracurricularActivities',
       'PlacementTraining', 'SSC_Marks', 'HSC_Marks', 'PlacementStatus'],
      dtype='object')

In [12]:
# Convert Yes/No to 1/0
df = df.replace({
    "Yes": 1,
    "No": 0
})

# Convert target column
df["PlacementStatus"] = df["PlacementStatus"].map({
    "Placed": 1,
    "NotPlaced": 0
})

# Remove StudentID if exists (safe check)
if "StudentID" in df.columns:
    df = df.drop(columns=["StudentID"])

# Split X and y
X = df.drop("PlacementStatus", axis=1)
y = df["PlacementStatus"]

# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

C:\Users\Tanuj Bansal\AppData\Local\Temp\ipykernel_17664\268389199.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({

In [13]:
# Train model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

print("Model trained successfully ")

Model trained successfully

In [14]:
accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.7805

In [15]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.83      0.82      1172
           1       0.74      0.72      0.73       828

    accuracy                           0.78      2000
   macro avg       0.77      0.77      0.77      2000
weighted avg       0.78      0.78      0.78      2000

In [18]:
import pickle
pickle.dump(model, open("model/placement_model.pkl", "wb"))